### ISSUE TITLE
Example is failing in the Minishift local environment

### ISSUE THREAD

**Issue by ilterpehlivan** [fabric8-quickstarts/karaf-camel-rest-sql#29]
Hi,

I am trying to run this example in my local environment. I succesfully managing mvn install and mvn fabric8:deploy. However in the pod logs i am encountering following error:

2016-09-06 18:57:09,088 | INFO  | FelixStartLevel  | BlueprintExtender                | 12 - org.apache.aries.blueprint.core - 1.4.3 | No quiesce support is available, so blueprint components will not participate in quiesce operations
2016-09-06 18:57:09,764 | WARN  | FelixStartLevel  | FeaturesServiceImpl              | 17 - org.apache.karaf.features.core - 2.4.4 | Unable to add features repository mvn:org.apache.karaf.features/static/4.0.5/xml/features at startup
java.lang.IllegalArgumentException: Unrecognized root element: {http://karaf.apache.org/xmlns/features/v1.4.0}features
    at org.apache.karaf.features.internal.FeatureValidationUtil.validate(FeatureValidationUtil.java:77)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.validateRepository(FeaturesServiceImpl.java:213)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.internalAddRepository(FeaturesServiceImpl.java:255)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.start(FeaturesServiceImpl.java:1377)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.osgi.Activator.doStart(Activator.java:126)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.osgi.Activator$2.addingService(Activator.java:96)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.karaf.features.osgi.Activator$2.addingService(Activator.java:93)[17:org.apache.karaf.features.core:2.4.4]
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)[org.osgi.core-6.0.0.jar:]
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)[org.osgi.core-6.0.0.jar:]
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[org.osgi.core-6.0.0.jar:]
    at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)[org.osgi.core-6.0.0.jar:]
    at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)[org.osgi.core-6.0.0.jar:]
    at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)[org.osgi.core-6.0.0.jar:]
    at org.apache.karaf.features.osgi.Activator.start(Activator.java:111)[17:org.apache.karaf.features.core:2.4.4]
    at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.4.0.jar:]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
2016-09-06 18:57:11,457 | INFO  | FelixStartLevel  | Activator                        | 42 - org.ops4j.pax.web.pax-web-runtime - 3.2.4 | EventAdmin support is not available, no servlet events will be posted!
2016-09-06 18:57:11,459 | INFO  | FelixStartLevel  | Activator                        | 42 - org.ops4j.pax.web.pax-web-runtime - 3.2.4 | LogService support enabled, log events will be created.
2016-09-06 18:57:11,462 | INFO  | FelixStartLevel  | Activator                        | 42 - org.ops4j.pax.web.pax-web-runtime - 3.2.4 | Pax Web started
2016-09-06 18:57:11,624 | INFO  | FelixStartLevel  | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.4.3 | Bundle io.fabric8.quickstarts.karaf-camel-rest-sql is waiting for namespace handlers [http://camel.apache.org/schema/blueprint]
2016-09-06 18:57:11,990 | INFO  | pool-4-thread-1  | Server                           | 37 - org.eclipse.jetty.aggregate.jetty-all-server - 8.1.17.v20150415 | jetty-8.1.17.v20150415
2016-09-06 18:57:12,063 | INFO  | pool-4-thread-1  | JettyServerImpl                  | 41 - org.ops4j.pax.web.pax-web-jetty - 3.2.4 | Pax Web is started with it's default configuration most likely it's listening on port 8181
2016-09-06 18:57:12,091 | INFO  | pool-4-thread-1  | JettyServerImpl                  | 41 - org.ops4j.pax.web.pax-web-jetty - 3.2.4 | Pax Web available at [0.0.0.0]:[8080]
2016-09-06 18:57:12,097 | ERROR | FelixStartLevel  | kubernetes-client                | 53 - io.fabric8.kubernetes-client - 1.3.72 | [io.fabric8.kubernetes.client.handlers.KubernetesListHandler(1)] Error during instantiation of the implementation object
java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/model/EditableKubernetesList
    at java.lang.Class.getDeclaredConstructors0(Native Method)[:1.8.0_101]
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)[:1.8.0_101]
    at java.lang.Class.getConstructor0(Class.java:3075)[:1.8.0_101]
    at java.lang.Class.newInstance(Class.java:412)[:1.8.0_101]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:253)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:127)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:871)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:838)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:777)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:344)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.getService(Felix.java:3699)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.scr.impl.helper.BindMethod.getServiceObject(BindMethod.java:572)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2012)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.prebind(DependencyManager.java:400)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1439)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1119)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:807)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:850)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:419)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:376)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.BundleComponentActivator.initialize(BundleComponentActivator.java:172)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.BundleComponentActivator.<init>(BundleComponentActivator.java:120)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:258)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.Activator.access$000(Activator.java:45)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:185)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)[20:org.apache.felix.scr:1.8.2]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:479)[20:org.apache.felix.scr:1.8.2]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:414)[20:org.apache.felix.scr:1.8.2]
    at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)[20:org.apache.felix.scr:1.8.2]
    at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443)[20:org.apache.felix.scr:1.8.2]
    at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:916)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:835)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:517)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2172)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.4.0.jar:]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.model.EditableKubernetesList not found by io.fabric8.kubernetes-model [56]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_101]
    at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1415)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1595)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1525)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_101]
    ... 42 more

I have no idea what this is about, could you please help me ? do you also see same error in your local minishift setup ?

**Comment by ilterpehlivan** [comment]
Somehow this errors are ignored and after a while context starts running. I see the printed logs with the scheduled producer and consumer routes. So this errors not blocking the deployment.

However service is not working properly, here is the output:

[eiltpeh@localhost OSGI-INF]$ oc get routes
NAME                      HOST/PORT                                            PATH      SERVICE                   TERMINATION   LABELS
fabric8                   fabric8.192.168.99.100.xip.io                                  fabric8                                 provider=fabric8
fabric8-docker-registry   fabric8-docker-registry.192.168.99.100.xip.io                  fabric8-docker-registry                 provider=fabric8
fabric8-forge             fabric8-forge.192.168.99.100.xip.io                            fabric8-forge                           provider=fabric8
gogs                      gogs.192.168.99.100.xip.io                                     gogs                                    provider=fabric8
gogs-ssh                  gogs-ssh.192.168.99.100.xip.io                                 gogs-ssh                                provider=fabric8
jenkins                   jenkins.192.168.99.100.xip.io                                  jenkins                                 provider=fabric8
jenkins-jnlp              jenkins-jnlp.192.168.99.100.xip.io                             jenkins-jnlp                            provider=fabric8
karaf-camel-rest-sql      karaf-camel-rest-sql-default.192.168.99.100.xip.io             karaf-camel-rest-sql  
mysql                     mysql.xip.io                                                   mysql                                   provider=fabric8
nexus                     nexus.192.168.99.100.xip.io                                    nexus                                   provider=fabric8
router                    router.xip.io                                                  router                                  provider=fabric8

[eiltpeh@localhost OSGI-INF]$ curl http://karaf-camel-rest-sql-default.192.168.99.100.xip.io/books/
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

[eiltpeh@localhost OSGI-INF]$ curl http://karaf-camel-rest-sql-default.192.168.99.100.xip.io/camel-rest-sql/books/
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

I dont know if the application or the services are not working properly. Any idea ?

**Comment by davsclaus** [comment]
We just merged in upgrades to karaf 4.x. Maybe you can try with latest code again
